language: php
php:
  - 5.6
  - 5.5
  - 5.4
install:
  - composer self-update
  - composer global require "fxp/composer-asset-plugin:~1.0"
  - composer install --prefer-dist --dev
  - composer require --dev "codeception/codeception:2.0.*@dev"
before_script:
  - cd tests
script: ../vendor/bin/codecept run
